# Generated by Django 5.0.7 on 2025-08-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_farmer",
            field=models.BooleanField(default=False),
        ),
    ]
