# Generated by Django 5.0.7 on 2025-08-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0003_agent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={},
        ),
        migrations.RenameField(
            model_name="agent",
            old_name="address",
            new_name="locations",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="agent",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
